  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: app-cmf-dev
      ports:
        - "3000:3000"
      env_file:
        - .env
      volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
      command: yarn dev -H 0.0.0.0