FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./

RUN yarn install --frozen-lockfile && yarn cache clean

EXPOSE 3000

CMD ["yarn", "dev", "--webpack", "-H", "0.0.0.0"]