import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { Toaster } from "react-hot-toast";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Curso Matemática Fácil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full antialiased">
      <body
        className={`${spaceGrotesk.className} min-h-full flex flex-col`}
      >
        {children}
        
         <Toaster
          position="bottom-right"
          reverseOrder={false}
          toastOptions={{
            duration: 4000,

            style: {
              background: "#f3f0eb",
              color: "#1C1C1C",
              border: "1px solid #ffeecb",
            },

            success: {
              iconTheme: {
                primary: "#22c55e",
                secondary: "#fff",
              },
            },

            error: {
              iconTheme: {
                primary: "#ef4444",
                secondary: "#fff",
              },
            },
          }}
        />

      </body>
    </html>
  );
}