import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Curso Matemática Fácil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full antialiased">
      <body
        className={`${spaceGrotesk.className} min-h-full flex flex-col`}
      >
        {children}
      </body>
    </html>
  );
}