name: CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Check Versions
        run: |
          node -v
          corepack --version
          yarn -v

      - name: Install Dependecies
        run: yarn install --immutable

      - name: Generate Prisma
        run: yarn prisma generate

      - name: Type Check
        run: yarn tsc --noEmit

      - name: Build
        run: yarn build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Trigger Vercel Deploy
        run:   curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
